// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdpnlqzzxfyclfcxhwuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkcG5scXp6eGZ5Y2xmY3hod3V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MzUyODMsImV4cCI6MjA3MDIxMTI4M30.3WugQljK80EvaJAHkUZ7_zUjoq2eoc0U5tsZJZJAp_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});